# Generated by Django 5.0.8 on 2024-11-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedai", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="stock",
        ),
        migrations.AddField(
            model_name="product",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="menu_pict/"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[("Waiting", "Waiting"), ("Served", "Served")],
                default="Pending",
                max_length=10,
            ),
        ),
    ]
