# Generated by Django 5.1.2 on 2024-11-26 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kedai", "0002_remove_product_stock_product_picture_and_more"),
    ]

    operations = [
    ]
