# Generated by Django 5.1.2 on 2024-11-28 07:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedai", "0004_remove_product_stock_product_picture_cart_cartitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="admin",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="kedai.admin"
            ),
        ),
        migrations.AddField(
            model_name="kasir",
            name="admin",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="kedai.admin"
            ),
        ),
    ]
