# Generated by Django 5.1.2 on 2024-11-28 09:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kedai", "0005_remove_product_stock_customer_admin_kasir_admin_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product_id",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="admin",
        ),
        migrations.RemoveField(
            model_name="kasir",
            name="admin",
        ),
        migrations.AddField(
            model_name="customer",
            name="admin_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="kedai.admin"
            ),
        ),
        migrations.AddField(
            model_name="kasir",
            name="admin_id",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="kedai.admin"
            ),
        ),
        
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
